#ifndef GPIO_PRV_H_
#define GPIO_PRV_H_
#include "std_types.h"
#include "GPIO.h"

//GPIO REGISTERS STRUCTURE 
typedef volatile struct {
uint32 GPIOx_MODER;
uint32 GPIOx_OTYPER;
uint32 GPIOx_OSPEEDER;
uint32 GPIOx_PUPDR;
uint32 GPIOx_IDR;
uint32 GPIOx_ODR;
uint32 GPIOx_BSRR;
uint32 GPIOx_LCKR;
uint32 GPIOx_AFRL;
uint32 GPIOx_AFRH;
}GPOI_t;


//MAXIMUM PORTS AND PINS NUMBER IN STM32F401 
#define GPIO_MAX_PORT_NUM               6
#define GPIO_MAX_PIN_NUM                16

//GPIO PORTS INDEXES 
#define GPIO_PORT_A											0
#define GPIO_PORT_B											1
#define GPIO_PORT_C											2
#define GPIO_PORT_D											3
#define GPIO_PORT_E											4
#define GPIO_PORT_H  										5


//BASE ADDRESSES OF GPIO REGISTERS  
#define GPIOA_BASE_ADD     ((volatile GPOI_t*)0x40020000)
#define GPIOB_BASE_ADD     ((volatile GPOI_t*)0x40020400)
#define GPIOC_BASE_ADD     ((volatile GPOI_t*)0x40020800)
#define GPIOD_BASE_ADD     ((volatile GPOI_t*)0x40020C00)
#define GPIOE_BASE_ADD     ((volatile GPOI_t*)0x40021000)
#define GPIOH_BASE_ADD     ((volatile GPOI_t*)0x40021C00)

//ARRAY OF POINTERS TO STRUCTURES TO MAP THE ADDRESSES
static GPOI_t* Config_Arr[GPIO_MAX_PORT_NUM]={GPIOA_BASE_ADD,GPIOB_BASE_ADD,GPIOC_BASE_ADD,GPIOD_BASE_ADD,GPIOE_BASE_ADD,GPIOH_BASE_ADD};

//ALL PORTS MODER REGISTERS 
#define GPIO_PORTA_MODER    Config_Arr[GPIO_PORT_A]->GPIOx_MODER   
#define GPIO_PORTB_MODER    Config_Arr[GPIO_PORT_B]->GPIOx_MODER   
#define GPIO_PORTC_MODER    Config_Arr[GPIO_PORT_C]->GPIOx_MODER   
#define GPIO_PORTD_MODER    Config_Arr[GPIO_PORT_D]->GPIOx_MODER   
#define GPIO_PORTE_MODER    Config_Arr[GPIO_PORT_E]->GPIOx_MODER   
#define GPIO_PORTH_MODER    Config_Arr[GPIO_PORT_H]->GPIOx_MODER   

//ALL PORTS OTYPER REGISTERS 
#define GPIO_PORTA_OTYPER    Config_Arr[GPIO_PORT_A]->GPIOx_OTYPER   
#define GPIO_PORTB_OTYPER    Config_Arr[GPIO_PORT_B]->GPIOx_OTYPER   
#define GPIO_PORTC_OTYPER    Config_Arr[GPIO_PORT_C]->GPIOx_OTYPER   
#define GPIO_PORTD_OTYPER    Config_Arr[GPIO_PORT_D]->GPIOx_OTYPER   
#define GPIO_PORTE_OTYPER    Config_Arr[GPIO_PORT_E]->GPIOx_OTYPER   
#define GPIO_PORTH_OTYPER    Config_Arr[GPIO_PORT_H]->GPIOx_OTYPER

//ALL PORTS OSPEEDER REGISTERS 
#define GPIO_PORTA_OSPEEDER    Config_Arr[GPIO_PORT_A]->GPIOx_OSPEEDER   
#define GPIO_PORTB_OSPEEDER    Config_Arr[GPIO_PORT_B]->GPIOx_OSPEEDER 
#define GPIO_PORTC_OSPEEDER    Config_Arr[GPIO_PORT_C]->GPIOx_OSPEEDER 
#define GPIO_PORTD_OSPEEDER    Config_Arr[GPIO_PORT_D]->GPIOx_OSPEEDER 
#define GPIO_PORTE_OSPEEDER    Config_Arr[GPIO_PORT_E]->GPIOx_OSPEEDER 
#define GPIO_PORTH_OSPEEDER    Config_Arr[GPIO_PORT_H]->GPIOx_OSPEEDER

//ALL PORTS PUPDR REGISTERS 
#define GPIO_PORTA_PUPDR    Config_Arr[GPIO_PORT_A]->GPIOx_PUPDR   
#define GPIO_PORTB_PUPDR    Config_Arr[GPIO_PORT_B]->GPIOx_PUPDR 
#define GPIO_PORTC_PUPDR    Config_Arr[GPIO_PORT_C]->GPIOx_PUPDR 
#define GPIO_PORTD_PUPDR    Config_Arr[GPIO_PORT_D]->GPIOx_PUPDR 
#define GPIO_PORTE_PUPDR    Config_Arr[GPIO_PORT_E]->GPIOx_PUPDR 
#define GPIO_PORTH_PUPDR    Config_Arr[GPIO_PORT_H]->GPIOx_PUPDR


//ALL PORTS IDR REGISTERS 
#define GPIO_PORTA_IDR   Config_Arr[GPIO_PORT_A]->GPIOx_IDR   
#define GPIO_PORTB_IDR   Config_Arr[GPIO_PORT_B]->GPIOx_IDR 
#define GPIO_PORTC_IDR   Config_Arr[GPIO_PORT_C]->GPIOx_IDR 
#define GPIO_PORTD_IDR   Config_Arr[GPIO_PORT_D]->GPIOx_IDR 
#define GPIO_PORTE_IDR   Config_Arr[GPIO_PORT_E]->GPIOx_IDR 
#define GPIO_PORTH_IDR   Config_Arr[GPIO_PORT_H]->GPIOx_IDR

//ALL PORTS ODR REGISTERS 
#define GPIO_PORTA_ODR   Config_Arr[GPIO_PORT_A]->GPIOx_ODR   
#define GPIO_PORTB_ODR   Config_Arr[GPIO_PORT_B]->GPIOx_ODR 
#define GPIO_PORTC_ODR   Config_Arr[GPIO_PORT_C]->GPIOx_ODR 
#define GPIO_PORTD_ODR   Config_Arr[GPIO_PORT_D]->GPIOx_ODR 
#define GPIO_PORTE_ODR   Config_Arr[GPIO_PORT_E]->GPIOx_ODR 
#define GPIO_PORTH_ODR   Config_Arr[GPIO_PORT_H]->GPIOx_ODR

//ALL PORTS BSRR REGISTERS 
#define GPIO_PORTA_BSRR   Config_Arr[GPIO_PORT_A]->GPIOx_BSRR   
#define GPIO_PORTB_BSRR   Config_Arr[GPIO_PORT_B]->GPIOx_BSRR 
#define GPIO_PORTC_BSRR   Config_Arr[GPIO_PORT_C]->GPIOx_BSRR 
#define GPIO_PORTD_BSRR   Config_Arr[GPIO_PORT_D]->GPIOx_BSRR 
#define GPIO_PORTE_BSRR   Config_Arr[GPIO_PORT_E]->GPIOx_BSRR 
#define GPIO_PORTH_BSRR   Config_Arr[GPIO_PORT_H]->GPIOx_BSRR

//ALL AFL  REGISTERS 
#define GPIO_PORTA_AFL  Config_Arr[GPIO_PORT_A]->GPIOx_AFRL  
#define GPIO_PORTB_AFL  Config_Arr[GPIO_PORT_B]->GPIOx_AFRL
#define GPIO_PORTC_AFL  Config_Arr[GPIO_PORT_C]->GPIOx_AFRL
#define GPIO_PORTD_AFL  Config_Arr[GPIO_PORT_D]->GPIOx_AFRL
#define GPIO_PORTE_AFL  Config_Arr[GPIO_PORT_E]->GPIOx_AFRL
#define GPIO_PORTH_AFL  Config_Arr[GPIO_PORT_H]->GPIOx_AFRL


//ALL AFH  REGISTERS 
#define GPIO_PORTA_AFH  Config_Arr[GPIO_PORT_A]->GPIOx_AFRH  
#define GPIO_PORTB_AFH  Config_Arr[GPIO_PORT_B]->GPIOx_AFRH
#define GPIO_PORTC_AFH  Config_Arr[GPIO_PORT_C]->GPIOx_AFRH
#define GPIO_PORTD_AFH  Config_Arr[GPIO_PORT_D]->GPIOx_AFRH
#define GPIO_PORTE_AFH  Config_Arr[GPIO_PORT_E]->GPIOx_AFRH
#define GPIO_PORTH_AFH  Config_Arr[GPIO_PORT_H]->GPIOx_AFRH
#endif
